CREATE USER 'hyubuki'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'hyubuki'@'%' WITH GRANT OPTION;

CREATE USER 'hyubuki'@'localhost' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON *.* TO 'hyubuki'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;
